name: Test create-verified-tag action
on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  sign-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: none
    outputs:
      tag: ${{ steps.sign-tag.outputs.tag }}
    steps:
      - name: Setup git for github app
        id: setup-git
        uses: EltonChou/setup-git-as-github-app@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.setup-git.outputs.token }}
          fetch-depth: 0

      - name: Create signed tag
        id: sign-tag
        uses: EltonChou/create-verified-tag@main
        with:
          tag: "test-tag-${{ github.run_number }}"
          message: "Test"
          git-user-email: "plscd748@gmail.com"
          git-user-name: ${{ steps.setup-git.outputs.user-name }}
          # git-user-email: ${{ steps.setup-git.outputs.user-email }}
          github-token: ${{ steps.setup-git.outputs.token }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

  verify-tag:
    runs-on: ubuntu-latest
    needs:
      - sign-tag
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify signed tag
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          git verify-tag ${{ needs.sign-tag.outputs.tag }}
