name: Test create-verified-tag action
on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: none
    steps:
      - name: Setup git for github app
        id: setup-git
        uses: EltonChou/setup-git-as-github-app@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.setup-git.outputs.token }}
          fetch-depth: 0

      - name: Create signed tag
        uses: EltonChou/create-verified-tag@main
        with:
          tag: "test-tag-${{ github.run_number }}"
          message: "Test"
          git-user-name: ${{ steps.setup-git.outputs.user-name }}
          git-user-email: ${{ steps.setup-git.outputs.user-email }}
          github-token: ${{ steps.setup-git.outputs.token }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
