name: Test create-verified-tag action

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  sign-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: none
    outputs:
      tag: ${{ steps.tagging.outputs.tag }}
    steps:
      - name: Setup git for github app
        id: setup-git
        uses: EltonChou/setup-git-as-github-app@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.setup-git.outputs.token }}
          fetch-depth: 0

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          trust_level: 5
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true
          git_committer_name: ${{ steps.setup-git.outputs.user-name }}
          git_committer_email: ${{ steps.setup-git.outputs.user-email }}

      - name: Tagging
        id: tagging
        shell: bash
        run: |
          TAG=test-tag-${{ github.run_number }}
          git tag -s $TAG -m "This is a test tag"
          git push origin $TAG
          echo "tag=$TAG" >> $GIT_OUTPUT

  verify-tag:
    runs-on: ubuntu-latest
    needs:
      - sign-tag
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify signed tag
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          git verify-tag ${{ needs.sign-tag.outputs.tag }}
